spring:
  application:
    name: Evolution

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/evolution?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/${ENTRA_TENANT_ID:38402fde-23c3-4417-97d7-b4410232a9ea}/
          audiences: api://${ENTRA_CLIENT_ID:0a1d5147-34e1-417b-9cb1-657286aca5bb}

evolution:
  auto-admins: ${AUTO_ADMIN_EMAILS:}
  cors-origins: ${CORS_ORIGINS:http://localhost:3000}

server:
  port: 8080