spring:
  application:
    name: Evolution

  profiles:
    active: dev  # Default to dev profile for local development

  datasource:
    url: jdbc:mysql://localhost:3306/evolution?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
