spring:
  application:
    name: Evolution

  profiles:
    active: dev  # Default to dev profile for local development

  datasource:
    url: jdbc:mysql://localhost:3306/evolution?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/38402fde-23c3-4417-97d7-b4410232a9ea/
          audiences: api://0a1d5147-34e1-417b-9cb1-657286aca5bb

server:
  port: 8080
